/*
 * MineSweeperAboutBox.java
 */
package minesweeper;

import gamelogic.Functions;
import java.awt.Font;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import org.jdesktop.application.Action;

public class MineSweeperAboutBoxHighScore extends javax.swing.JDialog {

    HighScore highScore;

    public MineSweeperAboutBoxHighScore(java.awt.Frame parent, HighScore highScore) {
        super(parent);
        this.highScore = highScore;
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        loadHighScores();
    }

    private void loadHighScores() {
        List<HighScore> allHighScores = (LinkedList<HighScore>) Functions.loadHighScores();
        List<HighScore> highScores = new LinkedList<HighScore>();
        boolean written[];
        for (HighScore tempHighScore : allHighScores) {
            if (highScore.isItSameType(tempHighScore)) {
                highScores.add(tempHighScore);
            }
        }

        written = new boolean[highScores.size()];
        for (int i = 0; i < written.length; i++) {
            written[i] = false;
        }

        writeHead();

        for (int i = 0; i < highScores.size(); i++) {
            long min = Long.MAX_VALUE;
            int position = 0;
            for (int j = 0; j < highScores.size(); j++) {
                if ((highScores.get(j).getTime() < min) && (written[j] == false)){
                    min = highScores.get(j).getTime();
                    position = j;
                }
            }
            writeHighScore(highScores.get(position),i);
            written[position] = true;
            if (i > 10){
                break;
            }
        }
    }

    public void writeHead(){
        JLabel label = new JLabel();

        label = new JLabel();
        label.setBounds(20, 80, 100, 20);
        label.setText("Name");
        label.setFont(new Font("Tahoma",Font.BOLD,12));
        this.add(label);        

        label = new JLabel();
        label.setBounds(20 + 120, 80, 100, 20);
        label.setText("Time");
        label.setFont(new Font("Tahoma",Font.BOLD,12));
        this.add(label);
    }

    public void writeHighScore(HighScore highScore, int order){
        JLabel label = new JLabel();

        label = new JLabel();
        label.setBounds(20, 100 + order*20, 100, 20);
        label.setText(highScore.getName());
        this.add(label);

        label = new JLabel();
        label.setBounds(20, 100 + order*20, 100, 20);
        label.setText(highScore.getName());
        this.add(label);

        label = new JLabel();
        label.setBounds(20 + 120, 100 + order*20, 100, 20);
        label.setText(Long.toString(highScore.getTime()/1000) + "." + ((highScore.getTime()/10) % 100));
        this.add(label);
    }

    @Action
    public void closeAboutBox() {
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(minesweeper.MineSweeperApp.class).getContext().getActionMap(MineSweeperAboutBoxHighScore.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(minesweeper.MineSweeperApp.class).getContext().getResourceMap(MineSweeperAboutBoxHighScore.class);
        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(closeButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addGap(290, 290, 290)
                .addComponent(closeButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
